[package]
name = "ppi_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
colorous = "1.0"
image = "0.24"
rayon = "1.10"
num_cpus = "1.16"
